---
title: "Lab 3"
author: "Magnus Wood"
date: "October 3rd, 2021"
output:
  word_document:h
    reference_docx: word-template.docx
  html_document:
    df_print: paged
always_allow_html: yes
---

```{r r-markdown_references, echo=FALSE, warning=FALSE}
# Rmarkdown to docx instructions
# https://rmarkdown.rstudio.com/articles_docx.html
# https://bookdown.org/yihui/rmarkdown/word-document.html

# R-Markdown: The Definitive Guide
# https://bookdown.org/yihui/rmarkdown/
```


```{r install_packages, echo=FALSE, warning=FALSE}
# install.packages("pacman")
pacman::p_load(tidyverse, ggpubr, bookdown, vtable)
#webshot::install_phantomjs()

```

```{r load_data, echo=FALSE, warning=FALSE}
# data was collected outside from 12:20 until 15:20
lab3_df <- read_csv("lab3_b.csv", show_col_types = FALSE)


column_names <- c("TIMESTAMP","RECORD","Solar_W/m2","AirTemp_dC","Vapor_Pressure_kPa","AtmPressure_kPa","RelHumidity","WindSpeed_m/s","WindDirection")

my_df <- lab3_df %>% 
  separate(TIMESTAMP, into = c("date", "time"), sep = " ") %>%
  separate(time, into = c("hours", "minutes", NA), sep=":") %>%
  mutate(time_m = (as.numeric(hours) - 12) * 60 + as.numeric(minutes) - 20) %>%
  filter(time_m <= 180) %>%
  mutate(time = paste(hours, ":", minutes, sep="")) %>%
  select("time", "Solar_W/m2", "AirTemp_dC", "RelHumidity", "WindSpeed_m/s")


names(my_df) <- c("time", "solar", "airtemp", "humidity", "windspeed")

```

## Summary Table
```{r Table1_summary, echo=FALSE, fig.cap="Table 1. Summary statistics of ATMOS41 data"}
#Getting complex
labs <- c('solar radiation (W/m2)',
    'air temperature',
    'numeric % of population over 75',
    NA,
    'numeric % growth rate of dpi')
sumtable(LifeCycleSavings,labels=labs)
st(my_df, col.breaks = 4,
   summ = list(
     c('notNA(x)','mean(x)','sd(x)','min(x)','max(x)'),
     c('notNA(x)','mean(x)')
   ),
   summ.names = list(
     c('N','Mean','SD','Min','Max'),
     c('Count','Percent')
   ))
```

```{r Fig1_plotoftwoparameters, echo=FALSE, fig.asp=.5, fig.cap='Figure 1. plot plot plotty plot'}

```
